compose:
  active: true
  ModifierHeightWithText:
    active: true
  ReusedModifierInstance:
    active: true
  PublicComposablePreview:
    active: true
  ModifierParameterPosition:
    active: true
  ComposableEventParameterNaming:
    active: false
  UnnecessaryEventHandlerParameter:
    active: true
  ComposableParametersOrdering:
    active: true
  ModifierDefaultValue:
    active: true
  MissingModifierDefaultValue:
    active: true
  TopLevelComposableFunctions:
    active: false
